import type { HtxhProfile, Profile } from "./types";

export const defaultEmptyProfile: Partial<Profile> = {
	stt: 0,
	name: "",
	dob: "",
	gender: "Nam",
	cccd: "",
	ethnicity: "",
	residence: "",
	currentAddress: "",
	age60: "",
	age65: "",
	age70: "",
	age75: "",
	age80: "",
	age85: "",
	age90: "",
	age95: "",
	age100: "",
	ageOver100: "",
	received: 0,
	notes: "",
};

export const defaultEmptyHtxhProfile: Partial<HtxhProfile> = {
	stt: 0,
	name: "",
	dob: "",
	gender: "Nam",
	cccd: "",
	ethnicity: "",
	residence: "",
	currentAddress: "",
	age75plus: "",
	age70to74poor: "",
	baoTro: "",
	huuTri: "",
	huuTuatBaoHiem: "",
	nguoiCoCong: "",
	received: 0,
	notes: "",
};

export const FIELD_LABELS: Record<string, string> = {
	name: "Họ và tên",
	dob: "Năm sinh",
	cccd: "Số CCCD",
	gender: "Giới tính",
	ethnicity: "Dân tộc",
	residence: "Cư trú (Hộ khẩu)",
	currentAddress: "Nơi ở hiện nay",
	age60: "Tròn 60 tuổi",
	age65: "Tròn 65 tuổi",
	age70: "Tròn 70 tuổi",
	age75: "Tròn 75 tuổi",
	age80: "Tròn 80 tuổi",
	age85: "Tròn 85 tuổi",
	age90: "Tròn 90 tuổi",
	age95: "Tròn 95 tuổi",
	age100: "Tròn 100 tuổi",
	ageOver100: "Trên 100 tuổi",
	age75plus: "Đủ 75 tuổi trở lên",
	age70to74poor: "Từ 70-74 tuổi hộ nghèo/cận nghèo",
	baoTro: "Đang hưởng Bảo trợ",
	huuTri: "Đang hưởng Hưu trí",
	huuTuatBaoHiem: "Đang hưởng Hưu, Tuất Bảo hiểm",
	nguoiCoCong: "Đang hưởng Người có công",
	received: "Trạng thái nhận quà",
	notes: "Ghi chú",
	stt: "Số thứ tự",
};

// 14 Dân tộc Xã Đăk Hà
export const DAKHA_ETHNICITIES = [
	"Kinh",
	"Xơ Đăng",
	"Gia Rai",
	"Giẻ Triêng",
	"Cor",
	"Cơ Ho",
	"Dao",
	"Dìu",
	"Ê Đê",
	"Giơ Lâng",
	"Ha Lăng",
	"Hoa",
	"Hrê",
	"Khách Gia",
] as const;
